In [2]:
import tensorflow as tf
from keras.utils import np_utils
import matplotlib.pyplot as plt
import numpy as np

In [3]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.cifar10.load_data()

In [4]:
print("Training images {}".format(x_train.shape))
print("Testing images {}".format(x_test.shape))

Training images (50000, 32, 32, 3)
Testing images (10000, 32, 32, 3)


In [5]:
y_train.shape

(50000, 1)

In [6]:
y_test.shape

(10000, 1)

In [7]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [ ]:
for i in range(220,225):
    plt.subplot(200+1+i)
    img=x_train[i]
    plt.imshow(img)
    plt.show()

In [8]:
x_train=x_train.reshape(x_train.shape[0],32,32,3)
x_test=x_test.reshape(x_test.shape[0],32,32,3)
x_train=x_train.astype("float32")
x_test=x_test.astype("float32")

x_train/=255
x_test/=255
n_class=10

print("Shape before one hot encoding",y_train.shape)
y_train=np_utils.to_categorical(y_train,n_class)
y_test=np_utils.to_categorical(y_test,n_class)
print("Shape after one hot encoding",y_train.shape)

Shape before one hot encoding (50000, 1)
Shape after one hot encoding (50000, 10)


In [9]:
print("Shape after one hot encoding",y_test.shape)

Shape after one hot encoding (10000, 10)


In [10]:
x_train

array([[[[0.23137255, 0.24313726, 0.24705882],
         [0.16862746, 0.18039216, 0.1764706 ],
         [0.19607843, 0.1882353 , 0.16862746],
         ...,
         [0.61960787, 0.5176471 , 0.42352942],
         [0.59607846, 0.49019608, 0.4       ],
         [0.5803922 , 0.4862745 , 0.40392157]],

        [[0.0627451 , 0.07843138, 0.07843138],
         [0.        , 0.        , 0.        ],
         [0.07058824, 0.03137255, 0.        ],
         ...,
         [0.48235294, 0.34509805, 0.21568628],
         [0.46666667, 0.3254902 , 0.19607843],
         [0.47843137, 0.34117648, 0.22352941]],

        [[0.09803922, 0.09411765, 0.08235294],
         [0.0627451 , 0.02745098, 0.        ],
         [0.19215687, 0.10588235, 0.03137255],
         ...,
         [0.4627451 , 0.32941177, 0.19607843],
         [0.47058824, 0.32941177, 0.19607843],
         [0.42745098, 0.28627452, 0.16470589]],

        ...,

        [[0.8156863 , 0.6666667 , 0.3764706 ],
         [0.7882353 , 0.6       , 0.13333334]

In [11]:
x_train.shape

(50000, 32, 32, 3)

In [12]:
x_test.shape

(10000, 32, 32, 3)

In [13]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [14]:
x_test

array([[[[0.61960787, 0.4392157 , 0.19215687],
         [0.62352943, 0.43529412, 0.18431373],
         [0.64705884, 0.45490196, 0.2       ],
         ...,
         [0.5372549 , 0.37254903, 0.14117648],
         [0.49411765, 0.35686275, 0.14117648],
         [0.45490196, 0.33333334, 0.12941177]],

        [[0.59607846, 0.4392157 , 0.2       ],
         [0.5921569 , 0.43137255, 0.15686275],
         [0.62352943, 0.44705883, 0.1764706 ],
         ...,
         [0.53333336, 0.37254903, 0.12156863],
         [0.49019608, 0.35686275, 0.1254902 ],
         [0.46666667, 0.34509805, 0.13333334]],

        [[0.5921569 , 0.43137255, 0.18431373],
         [0.5921569 , 0.42745098, 0.12941177],
         [0.61960787, 0.43529412, 0.14117648],
         ...,
         [0.54509807, 0.38431373, 0.13333334],
         [0.50980395, 0.37254903, 0.13333334],
         [0.47058824, 0.34901962, 0.12941177]],

        ...,

        [[0.26666668, 0.4862745 , 0.69411767],
         [0.16470589, 0.39215687, 0.5803922 ]

In [15]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten

model=Sequential()
#convolution layers
model.add(Conv2D(60, kernel_size=(3,3), strides=(1,1), padding="same", activation="relu", input_shape=(32,32,3)))

model.add(Conv2D(85, kernel_size=(3,3), strides=(1,1), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(135, kernel_size=(3,3), strides=(1,1), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())

#hidden layers
model.add(Dense(500,activation="relu"))
model.add(Dropout(0.4))
model.add(Dense(250,activation="relu"))
model.add(Dropout(0.3))
#output layer
model.add(Dense(10,activation="softmax"))
#compiling
model.compile(loss="categorical_crossentropy", metrics=["accuracy"], optimizer="adam")

model.fit(x_train,y_train,batch_size=128,epochs=10,validation_data=(x_test,y_test))

In [ ]:
classes=range(0,10)

names=["airplane",
      "automobile",
      "bird",
      "cat",
      "deer",
      "dog",
      "frog",
      "horse",
      "ship",
      "truck"]
class_labels=dict(zip(classes,names))
batch=x_test[250:260]
labels=np.argmax(y_test[250:260],axis=-1)

predictions=model.predict(batch,verbose=1)

In [ ]:
print(predictions)

In [ ]:
result=np.argmax(predictions,axis=-1)
print(result)

In [ ]:
fig,axs =plt.subplots(5,2,figsize=(19,6))
fig.subplots_adjust(hspace=1)
axs=axs.flatten()

for i,img in enumerate(batch):
    for key,value in class_labels.items():
        if result[i]==key:
            title="Prediction: {}\nActual: {}".format(class_labels[key],class_labels[labels[i]])
            axs[i].set_title(title)
            axs[i].axes.get_xaxis().set_visible(False)
            axs[i].axes.get_yaxis().set_visible(False)
    axs[i].imshow(img)
    
plt.show()